version: '3'

services:
  binder_postgresql:
    image: postgres:15.3
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=binder_all
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ../db/init.sql:/docker-entrypoint-initdb.d/init.sql

  binder_redis:
    image: redis:7.0.12
    ports:
      - "6379:6379"

  binder_api:
    build:
      context: ../api
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - binder_postgresql
      - binder_redis

volumes:
  postgres_data: