FROM confluentinc/cp-kafka-connect:6.2.0
RUN confluent-hub install --no-prompt --component-dir /usr/share/confluent-hub-components debezium/debezium-connector-postgresql:2.1.4
RUN confluent-hub install --no-prompt --component-dir /usr/share/confluent-hub-components confluentinc/kafka-connect-elasticsearch:14.0.8
