apiVersion: v1
kind: Pod
metadata:
  name: debug-pod
spec:
  containers:
  - name: debug-container
    image: busybox
    command:
      - sleep
      - "3600"
    volumeMounts:
    - name: varlog
      mountPath: /var/log/containers/
  volumes:
  - name: varlog
    hostPath:
      path: /var/log/containers/
  restartPolicy: Never
