apiVersion: apps/v1
kind: Deployment
metadata:
  name: binder-elasticsearch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: binder-elasticsearch
  template:
    metadata:
      labels:
        app: binder-elasticsearch
    spec:
      securityContext:
        fsGroup: 1000
      initContainers:
      - name: file-permissions
        image: busybox
        command: ['chown', '-R', '1000:1000', '/usr/share/elasticsearch/']
        volumeMounts:
        - mountPath: /usr/share/elasticsearch/data
          name: es-data
        securityContext:
          privileged: true
          runAsUser: 0
      containers:
      - name: binder-elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:7.17.10
        env:
        - name: discovery.type
          value: "single-node"
        - name: ES_JAVA_OPTS
          value: "-Xms512m -Xmx512m"
        ports:
        - containerPort: 9200
        volumeMounts:
        - name: es-data
          mountPath: /var/lib/elasticsearch/data
      volumes:
      - name: es-data
        persistentVolumeClaim:
          claimName: es-pvc