apiVersion: v1
kind: Service
metadata:
  name: binder-elasticsearch
spec:
  selector:
    app: binder-elasticsearch
  ports:
    - protocol: TCP
      port: 9200
      targetPort: 9200
  type: ClusterIP