apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
data:
  fluentd.conf: |
    <source>
      @type tail
      path /var/log/containers/*binder-api*.log
      pos_file /var/log/fluentd-binder-api.log.pos
      tag binder-api.*
      format /^(?<time>[^ ]+) (?<stream>stdout|stderr) F (?<log>.*)$/
      time_format %Y-%m-%dT%H:%M:%S.%NZ
      read_from_head true
    </source>

    <filter binder-api.*>
      @type parser
      key_name log
      format json
      reserve_data true
    </filter>

    <match binder-api.*>
      @type elasticsearch
      host binder-elasticsearch
      port 9200
      logstash_format true
      logstash_prefix binder-api
    </match>
