apiVersion: apps/v1
kind: Deployment
metadata:
  name: binder-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: binder-redis
  template:
    metadata:
      labels:
        app: binder-redis
    spec:
      containers:
      - name: redis
        image: redis:7.0.12
        ports:
        - containerPort: 6379