# get app revision
GET http://localhost:8080/app-revision HTTP/2.0

###

#get all users
GET http://localhost:8080/user/list HTTP/2.0

###
POST http://localhost:8080/user HTTP/2.0
content-type: application/json

{
    "FirstName": "Anna",
    "LastName": "Key",
    "PasswordHash": "pwdhash",
    "DisplayName": "Sweety Ann",
    "Country": "US",
    "Email": "anna.key123234131@testmail.com",
    "DateOfBirth": "2001-01-02",
    "Geolocation": "(41.866656420752399,-79.822251778096003)"
}