# get app revision
GET http://localhost:8080/app-revision HTTP/2.0

###

#get all users
GET http://localhost:8080/api/user/list HTTP/2.0

###
POST http://localhost:8080/api/user HTTP/2.0
content-type: application/json

{
    "FirstName": "Anna",
    "LastName": "Key",
    "PasswordHash": "pwdhash",
    "DisplayName": "Sweety Ann",
    "Country": "US",
    "Email": "anna.key{{$guid}}@testmail.com",
    "DateOfBirth": "2001-01-02",
    "Latitude": {{$randomInt -90 90}},
    "Longitude": {{$randomInt -180 180}}
}

###
PATCH http://localhost:8080/api/user-interests HTTP/2.0
content-type: application/json

{
    "UserId": {{$randomInt 0 100}},
    "Interests": [ "Pets", "Music", "Sport" ]
}

###
PATCH http://localhost:8080/api/user-photos HTTP/2.0
content-type: application/json

{
    "UserId": {{$randomInt 0 100}},
    "PhotoUrls": [ "https://images.unsplash.com/photo-1438761681033-6461ffad8d80", "https://images.unsplash.com/photo-1438761681033-6461ffad8d80" ]
}

### 
PATCH http://localhost:8080/api/user-filters HTTP/2.0
content-type: application/json 

{
    "UserId": {{$randomInt 0 100}},
    "MinDistanceKm": {{$randomInt 1 2}},
    "MaxDistanceKm": {{$randomInt 3 50}},
    "MinAge": {{$randomInt 16 25}},
    "MaxAge": {{$randomInt 26 55}}
}