name: Apply SQL script in binder_all

on:
    workflow_dispatch:
        inputs:
            file_name:
                description: 'sql script file name to apply'
                required: true

jobs:
    apply_sql:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Install doctl
              uses: digitalocean/action-doctl@v2
              with:
                token: ${{ secrets.DO_TOKEN }}

            - name: Save DigitalOcean kubeconfig with short-lived credentials
              run: doctl kubernetes cluster kubeconfig save --expiry-seconds 600 ${{ secrets.DO_CLUSTER_NAME }}

            - name: Get db pod
              run: |
                POD_NAME=$(kubectl get pods -l app=binder-postgresql -o jsonpath="{.items[0].metadata.name}")
                kubectl exec -i $POD_NAME -- psql -U postgres -d binder_all < ./db/${{ github.event.inputs.file_name }}