name: Build and push api docker image to Digital Ocean Container Registry

on:
    push:
        branches:
            - develop
        paths: 
            - 'api/src/**'

jobs:
    build-and-push:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v1

            - name: Login to Digital Oceat Container Registry
              run: echo "${{secrets.DO_TOKEN}}" | docker login -u ${{secrets.DO_TOKEN}} registry.digitalocean.com --password-stdin

            - name: Build and Push 
              uses: docker/build-push-action@v2
              with:
                push: true
                context: .
                file: ./api/Dockerfile
                build-args: BINDER_COMMIT_REVISION=${{github.sha}}
                tags: registry.digitalocean.com/${{secrets.DO_REGISTRY}}/binder-api:latest
                platform: linux/amd64
