name: Build and push api docker image to Digital Ocean Container Registry

on:
    push:
        branches:
            - develop
        paths: 
            - 'api/src/**'

jobs:
    build-and-push:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            
            - name: Install doctl
              uses: digitalocean/action-doctl@v2
              with:
                token: ${{ secrets.DO_TOKEN }}

            - name: Build and Push 
              run: docker build --build-arg BINDER_COMMIT_REVISION=${{github.sha}} -t registry.digitalocean.com/${{ secrets.DO_REGISTRY }}/binder-api:latest -f ./api/Dockerfile .
              
            - name: Log in to DigitalOcean Container Registry with short-lived credentials
              run: doctl registry login --expiry-seconds 1200

            - name: Push image to DigitalOcean Container Registry
              run: docker push registry.digitalocean.com/${{ secrets.DO_REGISTRY }}/binder-api:latest
